s1 = ("Teszt Elek")
print (s1)
print(s1[0])
print(s1[1])
print(s1[0:4])
print(s1[-1])
print(s1[0:-1])
print(s1[::2])
print(s1[::-1])
print(s1 + " a nevem")
print(s1 * 10)
print(s1.upper())
s1 = s1 + " a nevem, amit leírok"
print(s1)
print(s1.split())
print(s1.split("e"))
print("Ez egy teszt szöveg, berakok valamit ide: {}".format("alma"))
print("Ez egy teszt szöveg, berakok valamit ide: %s" %"alma")
print("elso: %s masodik: %s harmadik: %s" %("alma", "alma2", "alma3"))
print("elso: %s masodik: %s harmadik: %s" %("alma", "alma", "alma"))
#print("elso: {} masodik: {} harmadik: {}".format("alma"))
print("Egy %s" %"\talma")
print("Egy %r" %"\talma")
print("A szám: %s" %4.75)
print("A szám: %d" %4.75)
print("A szám: %f" %4.7512)
print("A szám: %10.2f" %4.7512)
print("elso: %s masodik: %6.3f harmadik: %r" %("almafa", 1.1234567, "\ncitrom"))
print("A szöveg: {} {} {}".format("alma", "barack", "citrom"))
print("A szöveg: {1} {2} {0}".format("alma", "barack", "citrom"))
print("A szöveg: {a} {b} {c}".format(a="alma", c="barack", b="citrom"))
print("{0:10} | {1} |".format("Kosár", "Mennyiség"))
print("{0:10} | {1:9} |".format("alma", 3))
print("{0:10} | {1:9} |".format("citrom", 1))
print("{0} | {1:9} |".format("paradicsom", 2))
print("-" *50)
print("{0:=<10} | {1} | {2:+>10}".format("Kosár", "Mennyiség", "Bolt"))
print("{0:=<10} | {1:*^9} | {2:+>10}".format("alma", 3, "Tesco"))
print("{0:=<10} | {1:*^9} | {2:+>10}".format("citrom", 1, "Spar"))
print("{0} | {1:*^9} | {2:+>10}".format("paradicsom", 2, "Aldi"))
print("A szám: {0:10.2f}".format(12.123456))
nev="\tJakab"
print(f"A nevem {nev!r}")
print(300 > 100)
print(300 < 100)
print(300 > 100)
print(100 == 100)
lista1 = ["alma", "barack", 12, True]
print(len(lista1))
print(lista1[0])
print(lista1[1:])
print(lista1[:3])
print(lista1 + ["új elem"])
lista1 = lista1 + ["új elem"]
print(lista1)
lista1.append("citrom")
print(lista1)
pop_valtozo = lista1.pop()
print(pop_valtozo)
print(lista1)
lista1.reverse()
print(lista1)
#lista1.sort()
#print(lista1)
lista1 = ["b", "a", "c", "d", "e", "f", "g", "h", "i", "j"]
lista1.sort()
print(lista1)

l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]
matrix = [l1, l2, l3]
print(matrix)
print(matrix[0])
print(matrix[1][1])
string_list = ["alma", "barack", "citrom"]
print(string_list)
print(string_list[2][3:6])

col1 = [cv[0] for cv in matrix]
print(col1)

print("-" *50)

val = input("Írjon be valamit: ")
list1 = list(val)
print(list1)
print("Az első és az utolsó eleme a %s és %s" %(list1[0], list1[-1]))
print("Az első és az utolsó elem kivételével a lista: %s" %list1[1:-1])
print("A listának %s eleme van" %len(list1))
print("A lista elemei szövegként: %s" %"".join(list1))
print("Szóközök mentén darabolás: %s" %val.split(" "))
#listázás

